/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 510 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package jdk.internal.event;

/**
 * A JFR event for native memory reallocations done via {@code Unsafe.reallocateMemory}.
 * <p>
 * This event is mirrored in {@code jdk.jfr.events.JavaNativeReallocateEvent}
 * where the event annotations are provided. The static methods
 * {@link #enabled()} and {@link #commit(long, long, long, long, long)} are
 * intercepted and rewritten by JFR when JFR is enabled.
 * <p>
 * Note that the order of the fields of this class must match the argument
 * order of the generated {@link #commit(long, long, long, long, long)} method,
 * with the first two parameters being the implicit {@code startTime} and
 * {@code duration} fields that JFR expects.
 */
public final class JavaNativeReallocateEvent extends Event {

    // THE ORDER OF THE FOLLOWING FIELDS IS IMPORTANT!
    // The order must match the argument order of the generated commit method:
    // startTime, duration, freeAddr, allocAddr, allocationSize
    public long freeAddr;
    public long allocAddr;
    public long allocationSize;

    /**
     * Determine if this kind of event is enabled. The implementation
     * of this method is generated automatically by JFR when enabled.
     *
     * @return true if this type of event is enabled, false otherwise
     */
    public static boolean enabled() {
        // Generated by JFR
        return false;
    }

    /**
     * Actually commit an event. The implementation is generated automatically
     * by JFR when the event is enabled. The order of the fields must be the
     * same as the parameters in this method. Because the implicit fields
     * {@code startTime} and {@code duration} are always emitted before the
     * declared fields, the first two {@code long} parameters must be
     * {@code startTime} and {@code duration} respectively.
     *
     * @param startTime       start time of the event (typically 0)
     * @param duration        duration of the reallocation in nanoseconds (typically 0)
     * @param freeAddr        address of the freed (old) native memory block
     * @param allocAddr       address of the allocated (new) native memory block
     * @param allocationSize  size in bytes of the new allocation
     */
    public static void commit(long startTime, long duration, long freeAddr, long allocAddr, long allocationSize) {
        // Generated by JFR
    }
}